In [ ]:
# 1. Mount Google Drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df_cancer=pd.read_csv('/content/drive/MyDrive/Breast_GSE45827.csv')
df_cancer.head()

,samples,type,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,...,AFFX-r2-Ec-bioD-3_at,AFFX-r2-Ec-bioD-5_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
0,84,basal,9.850040,8.097927,6.424728,7.353027,3.029122,6.880079,4.963740,4.408328,...,12.229711,11.852955,13.658701,13.477698,6.265781,5.016196,4.901594,2.966657,3.508495,3.301999
1,85,basal,9.861357,8.212222,7.062593,7.685578,3.149468,7.542283,5.129607,4.584418,...,12.178531,11.809408,13.750086,13.470146,6.771853,5.291005,5.405839,2.934763,3.687666,3.064299
2,87,basal,10.103478,8.936137,5.735970,7.687822,3.125931,6.562369,4.813449,4.425195,...,12.125108,11.725766,13.621732,13.295080,6.346952,5.171403,5.184286,2.847684,3.550597,3.158535
3,90,basal,9.756875,7.357148,6.479183,6.986624,3.181638,7.802344,5.490982,4.567956,...,12.111235,11.719215,13.743108,13.508861,6.610284,5.193356,5.086569,3.031602,3.524981,3.272665
4,91,basal,9.408330,7.746404,6.693980,7.333426,3.169923,7.610457,5.372469,4.424426,...,12.173642,11.861296,13.797774,13.542206,6.414354,5.040202,5.235318,2.956232,3.445501,3.193947

In [ ]:
df_cancer.tail()

,samples,type,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,...,AFFX-r2-Ec-bioD-3_at,AFFX-r2-Ec-bioD-5_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
146,230,luminal_B,10.392638,7.334408,6.848586,7.020486,3.228065,7.815439,5.448470,4.496955,...,12.638556,12.122129,14.331152,14.133976,8.495888,4.971727,6.209136,2.852852,3.697448,3.333289
147,233,luminal_B,10.930875,8.415294,5.906827,7.753572,3.270557,7.367931,5.906849,5.194349,...,12.523507,11.977970,14.285405,14.070989,8.193182,6.528948,7.108210,2.929800,3.833289,3.213893
148,236,luminal_B,11.027098,7.180876,6.304736,7.641197,3.206950,8.569296,5.823146,4.617309,...,12.256767,11.661126,14.149586,13.977076,8.351331,6.882504,7.329545,3.085127,3.628848,3.215807
149,237,luminal_B,10.444395,7.525153,5.964460,7.825939,3.384147,7.268454,5.245072,5.088004,...,12.321900,11.727694,14.186277,13.943521,7.927210,6.839086,7.089259,3.018525,3.770597,3.102298
150,238,luminal_B,11.345817,7.379299,5.891172,7.394586,3.183420,7.792885,5.355978,4.457914,...,12.126110,11.478893,14.070188,13.857547,7.992141,5.661898,6.460331,3.061585,3.857525,3.129827

In [ ]:
df_cancer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Columns: 54677 entries, samples to AFFX-TrpnX-M_at
dtypes: float64(54675), int64(1), object(1)
memory usage: 63.0+ MB

In [ ]:
# Upload file
from google.colab import files
uploaded = files.upload()

# Core libraries
import pandas as pd
import numpy as np

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Deep Learning
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Metrics
from sklearn.metrics import accuracy_score, classification_report

Saving Breast_GSE45827.csv to Breast_GSE45827.csv

In [13]:
print(df_cancer.shape)
print(df_cancer.columns)

(151, 54677)
Index(['samples', 'type', '1007_s_at', '1053_at', '117_at', '121_at',
       '1255_g_at', '1294_at', '1316_at', '1320_at',
       ...
       'AFFX-r2-Ec-bioD-3_at', 'AFFX-r2-Ec-bioD-5_at', 'AFFX-r2-P1-cre-3_at',
       'AFFX-r2-P1-cre-5_at', 'AFFX-ThrX-3_at', 'AFFX-ThrX-5_at',
       'AFFX-ThrX-M_at', 'AFFX-TrpnX-3_at', 'AFFX-TrpnX-5_at',
       'AFFX-TrpnX-M_at'],
      dtype='object', length=54677)

In [14]:

X = df_cancer.drop(columns=['samples', 'type'])
y = df_cancer['type']


le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Train shape:", X_train.shape)

Train shape: (120, 54675)

In [15]:
ann_model = keras.Sequential([
    layers.Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dropout(0.3),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(64, activation='relu'),

    layers.Dense(len(np.unique(y_encoded)), activation='softmax')
])

ann_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_ann = ann_model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=16,
    validation_split=0.2
)

y_pred_ann = np.argmax(ann_model.predict(X_test), axis=1)

print("ANN Accuracy:", accuracy_score(y_test, y_pred_ann))
print(classification_report(y_test, y_pred_ann))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 12s 827ms/step - accuracy: 0.5312 - loss: 3.5817 - val_accuracy: 0.8333 - val_loss: 2.1009
Epoch 2/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 593ms/step - accuracy: 0.7708 - loss: 3.2140 - val_accuracy: 0.8750 - val_loss: 1.1006
Epoch 3/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 372ms/step - accuracy: 0.8229 - loss: 4.8161 - val_accuracy: 0.8750 - val_loss: 2.0877
Epoch 4/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 390ms/step - accuracy: 0.8854 - loss: 2.2450 - val_accuracy: 0.8750 - val_loss: 2.3821
Epoch 5/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 358ms/step - accuracy: 0.8958 - loss: 1.5036 - val_accuracy: 0.9583 - val_loss: 0.1552
Epoch 6/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 447ms/step - accuracy: 0.9688 - loss: 0.9914 - val_accuracy: 1.0000 - val_loss: 1.5911e-05
Epoch 7/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 593ms/step - accuracy: 0.9583 - loss: 0.4914 - val_accuracy: 0.9583 - val_loss: 0.1367
Epoch 8/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 308ms/step - accuracy: 0.9688 - loss: 1.1336 - val_accuracy: 0.9167 - val_loss: 1.1459
Epoch 9/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 238ms/step - accuracy: 0.9167 - loss: 2.0590 - val_accuracy: 0.9583 - val_loss: 1.0801
Epoch 10/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 247ms/step - accuracy: 0.9688 - loss: 0.3626 - val_accuracy: 0.9583 - val_loss: 0.3984
Epoch 11/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 241ms/step - accuracy: 0.9479 - loss: 1.3619 - val_accuracy: 1.0000 - val_loss: 1.9754e-05
Epoch 12/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 248ms/step - accuracy: 0.9688 - loss: 1.2569 - val_accuracy: 1.0000 - val_loss: 3.8799e-05
Epoch 13/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 391ms/step - accuracy: 0.9896 - loss: 0.3686 - val_accuracy: 1.0000 - val_loss: 2.9655e-04
Epoch 14/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 357ms/step - accuracy: 0.9583 - loss: 0.4942 - val_accuracy: 1.0000 - val_loss: 6.0147e-06
Epoch 15/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 303ms/step - accuracy: 0.9583 - loss: 0.8326 - val_accuracy: 0.9583 - val_loss: 0.3540
Epoch 16/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 242ms/step - accuracy: 0.9792 - loss: 0.7030 - val_accuracy: 0.9167 - val_loss: 1.1166
Epoch 17/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 324ms/step - accuracy: 0.9896 - loss: 0.0390 - val_accuracy: 0.9167 - val_loss: 3.5109
Epoch 18/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 381ms/step - accuracy: 1.0000 - loss: 2.0048e-04 - val_accuracy: 0.9167 - val_loss: 4.6918
Epoch 19/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 399ms/step - accuracy: 0.9688 - loss: 0.5250 - val_accuracy: 0.9167 - val_loss: 4.8621
Epoch 20/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 576ms/step - accuracy: 0.9688 - loss: 1.5388 - val_accuracy: 0.9167 - val_loss: 3.8395
Epoch 21/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 426ms/step - accuracy: 0.9896 - loss: 0.4478 - val_accuracy: 0.9583 - val_loss: 1.8834
Epoch 22/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 641ms/step - accuracy: 1.0000 - loss: 1.6986e-06 - val_accuracy: 0.9583 - val_loss: 1.5731
Epoch 23/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 579ms/step - accuracy: 0.9583 - loss: 0.4102 - val_accuracy: 0.9583 - val_loss: 1.0061
Epoch 24/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 7s 855ms/step - accuracy: 1.0000 - loss: 6.2459e-07 - val_accuracy: 0.9583 - val_loss: 0.7271
Epoch 25/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 506ms/step - accuracy: 0.9583 - loss: 1.7313 - val_accuracy: 1.0000 - val_loss: 5.6843e-04
Epoch 26/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 267ms/step - accuracy: 0.9896 - loss: 0.6345 - val_accuracy: 1.0000 - val_loss: 0.0020
Epoch 27/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 246ms/step - accuracy: 0.9688 - loss: 1.2324 - val_accuracy: 1.0000 - val_loss: 5.7128e-04
Epoch 28/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 3s 248ms/step - accuracy: 0.9896 - loss: 0.0908 - val_accuracy: 1.0000 - val_loss: 6.4572e-08
Epoch 29/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 316ms/step - accuracy: 0.9896 - loss: 1.1981 - val_accuracy: 1.0000 - val_loss: 5.5134e-07
Epoch 30/30
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 626ms/step - accuracy: 0.9896 - loss: 0.3771 - val_accuracy: 0.9583 - val_loss: 0.0831
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step
ANN Accuracy: 0.8387096774193549
              precision    recall  f1-score   support

           0       0.57      0.80      0.67         5
           1       1.00      0.70      0.82        10
           2       1.00      1.00      1.00         5
           3       0.60      1.00      0.75         3
           4       1.00      0.86      0.92         7
           5       1.00      1.00      1.00         1

    accuracy                           0.84        31
   macro avg       0.86      0.89      0.86        31
weighted avg       0.89      0.84      0.85        31

In [17]:
# reshape
X_train_cnn = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test_cnn = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

In [18]:
cnn_model = keras.Sequential([
    layers.Conv1D(64, 3, activation='relu', input_shape=(X_train.shape[1], 1)),
    layers.MaxPooling1D(2),

    layers.Conv1D(32, 3, activation='relu'),
    layers.MaxPooling1D(2),

    layers.Flatten(),

    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),

    layers.Dense(len(np.unique(y_encoded)), activation='softmax')
])

cnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history_cnn = cnn_model.fit(
    X_train_cnn, y_train,
    epochs=20,
    batch_size=16,
    validation_split=0.2
)

y_pred_cnn = np.argmax(cnn_model.predict(X_test_cnn), axis=1)

print("CNN Accuracy:", accuracy_score(y_test, y_pred_cnn))
print(classification_report(y_test, y_pred_cnn))

Epoch 1/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 20s 3s/step - accuracy: 0.2396 - loss: 25.6704 - val_accuracy: 0.5833 - val_loss: 1.4923
Epoch 2/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 3s/step - accuracy: 0.5938 - loss: 1.5300 - val_accuracy: 0.7917 - val_loss: 0.6189
Epoch 3/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - accuracy: 0.8333 - loss: 0.5269 - val_accuracy: 0.9167 - val_loss: 0.6834
Epoch 4/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 20s 3s/step - accuracy: 0.9479 - loss: 0.4160 - val_accuracy: 0.8333 - val_loss: 0.6894
Epoch 5/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 3s/step - accuracy: 0.9583 - loss: 0.2840 - val_accuracy: 0.7917 - val_loss: 0.5339
Epoch 6/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 3s/step - accuracy: 0.9896 - loss: 0.1560 - val_accuracy: 0.8750 - val_loss: 0.3582
Epoch 7/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - accuracy: 1.0000 - loss: 0.0392 - val_accuracy: 0.8750 - val_loss: 0.2333
Epoch 8/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 25s 4s/step - accuracy: 0.9896 - loss: 0.0318 - val_accuracy: 0.8750 - val_loss: 0.2984
Epoch 9/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 3s/step - accuracy: 1.0000 - loss: 0.0108 - val_accuracy: 0.8750 - val_loss: 0.2142
Epoch 10/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 3s/step - accuracy: 0.9896 - loss: 0.0335 - val_accuracy: 0.9167 - val_loss: 0.1750
Epoch 11/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 20s 3s/step - accuracy: 1.0000 - loss: 0.0086 - val_accuracy: 0.7917 - val_loss: 0.4623
Epoch 12/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 3s/step - accuracy: 1.0000 - loss: 0.0109 - val_accuracy: 0.7500 - val_loss: 0.5824
Epoch 13/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 20s 3s/step - accuracy: 1.0000 - loss: 0.0115 - val_accuracy: 0.7500 - val_loss: 0.6060
Epoch 14/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.7917 - val_loss: 0.5316
Epoch 15/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 18s 3s/step - accuracy: 1.0000 - loss: 0.0087 - val_accuracy: 0.8333 - val_loss: 0.4184
Epoch 16/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 20s 3s/step - accuracy: 1.0000 - loss: 0.0040 - val_accuracy: 0.8750 - val_loss: 0.3608
Epoch 17/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 25s 4s/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9167 - val_loss: 0.3299
Epoch 18/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 36s 3s/step - accuracy: 1.0000 - loss: 9.0026e-04 - val_accuracy: 0.9167 - val_loss: 0.2996
Epoch 19/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 21s 3s/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9167 - val_loss: 0.2933
Epoch 20/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 17s 3s/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.9167 - val_loss: 0.2680
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
CNN Accuracy: 0.8709677419354839
              precision    recall  f1-score   support

           0       0.62      1.00      0.77         5
           1       1.00      0.80      0.89        10
           2       1.00      1.00      1.00         5
           3       0.75      1.00      0.86         3
           4       1.00      0.71      0.83         7
           5       1.00      1.00      1.00         1

    accuracy                           0.87        31
   macro avg       0.90      0.92      0.89        31
weighted avg       0.92      0.87      0.88        31

In [19]:
!pip install shap

Requirement already satisfied: shap in /usr/local/lib/python3.12/dist-packages (0.51.0)
Requirement already satisfied: numpy>=2 in /usr/local/lib/python3.12/dist-packages (from shap) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from shap) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from shap) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from shap) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap) (4.67.3)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.12/dist-packages (from shap) (26.0)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.12/dist-packages (from shap) (0.60.0)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.12/dist-packages (from shap) (0.43.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap) (3.1.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from shap) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->shap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->shap) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)

In [20]:
import shap